-- Create the gifts table
create table if not exists gifts (
  id bigint generated by default as identity primary key,
  name text not null,
  is_taken boolean default false,
  reserved_by text,
  created_at timestamp with time zone default now()
);


-- Create the confirmations table
create table if not exists confirmations (
  id bigint generated by default as identity primary key,
  name text not null,
  attendance text not null check (attendance in ('attending', 'not_attending', 'maybe')),
  message text,
  created_at timestamp with time zone default now()
);

-- Add this to allow anonymous inserts
ALTER TABLE confirmations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous inserts" ON confirmations
FOR INSERT TO anon
WITH CHECK (true);

CREATE POLICY "Allow anonymous reads" ON confirmations
FOR SELECT TO anon
USING (true);

-- Insert some sample gifts
insert into gifts (name) values
('Rice Cooker'),
('Stand Fan'),
('Kitchen Cookware (Pan)'),
('Kitchen Cookware (Pots)'),
('Kitchen Cookware (Kettle)'),
('Microwave Oven'),
('Drinking Glasses'),
('Dinner/Meal Plates (Preferably White)'),
('Electric Kettle'),
('Stand Mirror');