-- Create the gifts table
create table if not exists gifts (
  id bigint generated by default as identity primary key,
  name text not null,
  is_taken boolean default false,
  reserved_by text,
  created_at timestamp with time zone default now()
);

-- Insert some sample gifts
insert into gifts (name) values
('Rice Cooker'),
('Stand Fan'),
('Kitchen Cookware (Pan)'),
('Kitchen Cookware (Pots)'),
('Kitchen Cookware (Kettle)'),
('Microwave Oven'),
('Drinking Glasses'),
('Dinner/Meal Plates (Preferably White)'),
('Electric Kettle'),
('Stand Mirror');